var family_tree = [
    {
        id:'0101',
        parentId:null,
        name:'NGUYỄN QUÝ CÔNG',
        title:"HÀNG 1",
        description1:"THƯỢNG TỔ KHẢO: NGUYỄN QUÝ CÔNG HÚY PHÚC THIỆN THẦN VỊ KỴ NHẬT MỒNG HAI THÁNG CHẠP",
        description2:"THƯỢNG TỔ TỶ: VŨ QUÝ THỊ NHỤ NHÂN LINH VỊ KỴ NHẬT: MỒNG 5 THÁNG GIÊNG",
    },
    {
        id:'0201',
        parentId:"0101",
        name:'NGUYỄN QUÝ CÔNG',
        title:"HÀNG 2 ĐỆ TAM CHI",
        description1:"THỦY TỔ: NGUYỄN QUÝ CÔNG TỰ ĐỨC THỊNH KỴ NHẬT 15/10",
        description2:"TỔ TỶ: DOÃN QUÝ THỊ HIỆU TỪ TÂM LINH VỊ KỴ NHẬT 7/11",
    },
    {
        id:'0301',
        parentId:"0201",
        name:'NGUYỄN QUÝ CÔNG',
        title:"HÀNG 3",
        description1:"NGUYỄN QUÝ CÔNG TỰ HỮU KIỀU KỴ NHẬT 16 THÁNG CHẠP",
        description2:"BÙI QUÝ THỊ HIỆU TỪ TÍNH KỴ NHẬT 6 THÁNG CHẠP",
    },
    {
        id:'0401',
        parentId:"0301",
        name:'PHÁP TRỊ',
        title:"HÀNG 4",
        description1:"PHÁP TRỊ KỴ NHẬT 23/10",
        description2:"B1 BÙI QUÝ THỊ TRUNG CẨN KỴ NHẬT 1/4",
        description3:"B2 VŨ QUÝ THỊ HIỆU TỪ THUẦN KỴ NHẬT 19/2",
    },
    {
        id:'0402',
        parentId:"0301",
        name:'ĐÌNH NHÂN',
        title:"HÀNG 4",
        description1:"ĐÌNH NHÂN KỴ NHẬT 2/8",
        description2:"B1 VŨ QUÝ THỊ HÚY XUẤT KỴ NHẬT 16/9",
        description3:"B2 BÙI QUÝ THỊ HIỆU TỪ THÁI KỴ NHẬT 27/7",
    },
    {
        id:'0501',
        parentId:"0402",
        name:'NGUYỄN THÀNH CHÍNH',
        title:"HÀNG 5",
        description1:"NGUYỄN THÀNH CHÍNH KỴ NHẬT 29/3",
        description2:"VŨ THỊ HÚY HIỆU HẢO LẠC KỴ NHẬT 11/7",
        description3:"VŨ THỊ HÚY TINH KỴ NHẬT MỒNG 6 THÁNG GIÊNG",
    },
    {
        id:'0601',
        parentId:"0501",
        name:'KHẮC HÀI',
        title:"HÀNG 6",
        description1:"KHẮC HÀI KỴ NHẬT 4/9",
        description2:"LÊ THỊ NỨC HIỆU TỪ DƯỠNG KỴ NHẬT 6/5",
    },
    {
        id:'0602',
        parentId:"0501",
        name:'ĐỨC VINH',
        title:"HÀNG 6",
        description1:"ĐỨC VINH KỴ NHẬT 20 THÁNG CHẠP",
        description2:"VŨ QUÝ THỊ AN",
        description3:"LÊ THỊ HÚY NGUYỆN KỴ NHẬT 19/11",
    },
    {
        id:'0603',
        parentId:"0501",
        name:'TÍN THƯỞNG',
        title:"HÀNG 6",
        description1:"TÍN THƯỞNG KỴ NHẬT 17/12",
        description2:"VŨ THỊ HÚY LIÊN KỴ NHẬT 21/4",
        description3:"LÊ THỊ HÚY CỔN",
    },
    {
        id:'0604',
        parentId:"0501",
        name:'XUÂN ĐIỂM',
        title:"HÀNG 6",
        description1:"XUÂN ĐIỂM KỴ NHẬT 7/4",
        description2:"LÊ THỊ HÚY HÀI KỴ NHẬT 1/7",
        description3:"HOÀNG THỊ HÚY KHA KỴ NHẬT 30/4",
    },
    {
        id:'0701',
        parentId:"0602",
        name:'LÝ OẢN',
        title:"HÀNG 7",
    },
    {
        id:'0702',
        parentId:"0602",
        name:'LÝ HUÊ',
        title:"HÀNG 7",
    },
    {
        id:'0703',
        parentId:"0602",
        name:'THỦ DIỄN',
        title:"HÀNG 7",
    },
    {
        id:'0704',
        parentId:"0603",
        name:'LAN',
        title:"HÀNG 7",
    },
    {
        id:'0705',
        parentId:"0604",
        name:'TRÁNH ĐỒNG',
        title:"HÀNG 7",
    },
    {
        id:'0706',
        parentId:"0604",
        name:'KAI NHIÊN',
        title:"HÀNG 7",
    },
    {
        id:'0707',
        parentId:"0604",
        name:'LÝ BÚT',
        title:"HÀNG 7",
    },
    {
        id:'0708',
        parentId:"0604",
        name:'BÍNH BÉ',
        title:"HÀNG 7",
    },
    {
        id:'0801',
        parentId:"0701",
        name:'TRÁNH TẠ',
        title:"HÀNG 8",
    },
    {
        id:'0802',
        parentId:"0701",
        name:'LÝ TỘ',
        title:"HÀNG 8",
    },
    {
        id:'0803',
        parentId:"0702",
        name:'PHÓ CỦA',
        title:"HÀNG 8",
    },
    {
        id:'0804',
        parentId:"0702",
        name:'VĂN MẠO',
        title:"HÀNG 8",
    },
    {
        id:'0805',
        parentId:"0702",
        name:'VĂN CỎ',
        title:"HÀNG 8",
    },
    {
        id:'0806',
        parentId:"0702",
        name:'VĂN NÊN',
        title:"HÀNG 8",
        description1:"VĂN NÊN KỴ NHẬT 18/10",
        description2:"TRẦN THỊ MÔ",
        description3:"SINH 3 CON TRAI 3 CON GÁI",
    },
    {
        id:'0807',
        parentId:"0703",
        name:'ĐOÀN PHÁI',
        title:"HÀNG 8",
    },
    {
        id:'0808',
        parentId:"0703",
        name:'VĂN HỢI',
        title:"HÀNG 8",
        description1:"CƯ TRÚ MIỀN NAM",
    },
    {
        id:'0809',
        parentId:"0705",
        name:'VĂN LÉ',
        title:"HÀNG 8",
    },
    {
        id:'0810',
        parentId:"0706",
        name:'VĂN THƯ',
        title:"HÀNG 8",
        description1:"LIỆT SỸ CHỐNG PHÁP",
    },
    {
        id:'0811',
        parentId:"0706",
        name:'VĂN TUYỀN CHÚNG',
        title:"HÀNG 8",
    },
    {
        id:'0812',
        parentId:"0707",
        name:'VĂN NHẤT',
        title:"HÀNG 8",
    },
    {
        id:'0813',
        parentId:"0707",
        name:'VĂN NHỠ',
        title:"HÀNG 8",
    },
    {
        id:'0814',
        parentId:"0707",
        name:'VĂN TÝ',
        title:"HÀNG 8",
    },
    {
        id:'0815',
        parentId:"0708",
        name:'VĂN NHƯỢNG',
        title:"HÀNG 8",
        description1:"VĂN NHƯỢNG",
        description2:"NGUYỄN THỊ ĐÍCH",
    },
    {
        id:'0816',
        parentId:"0708",
        name:'VĂN BÁU',
        title:"HÀNG 8",
    },
    {
        id:'0901',
        parentId:"0801",
        name:'TỌA',
        title:"HÀNG 9",
    },
    {
        id:'0902',
        parentId:"0801",
        name:'TÒA',
        title:"HÀNG 9",
    },
    {
        id:'0903',
        parentId:"0801",
        name:'BẰNG',
        title:"HÀNG 9",
    },
    {
        id:'0904',
        parentId:"0801",
        name:'PHIỆT',
        title:"HÀNG 9",
    },
    {
        id:'0905',
        parentId:"0801",
        name:'PHIẾT',
        title:"HÀNG 9",
    },
    {
        id:'0906',
        parentId:"0802",
        name:'TIỄN',
        title:"HÀNG 9",
    },
    {
        id:'0907',
        parentId:"0802",
        name:'HẮNG',
        title:"HÀNG 9",
    },
    {
        id:'0908',
        parentId:"0803",
        name:'THANH',
        title:"HÀNG 9",
    },
    {
        id:'0909',
        parentId:"0803",
        name:'DŨNG',
        title:"HÀNG 9",
    },
    {
        id:'0910',
        parentId:"0804",
        name:'THÀNH',
        title:"HÀNG 9",
    },
    {
        id:'0911',
        parentId:"0805",
        name:'MIÊU',
        title:"HÀNG 9",
    },
    {
        id:'0912',
        parentId:"0806",
        name:'HƯNG',
        title:"HÀNG 9",
    },
    {
        id:'0913',
        parentId:"0806",
        name:'TOÀN',
        title:"HÀNG 9",
    },
    {
        id:'0914',
        parentId:"0806",
        name:'CẢNH',
        title:"HÀNG 9",
    },
    {
        id:'0915',
        parentId:"0807",
        name:'SƠN',
        title:"HÀNG 9",
    },
    {
        id:'0916',
        parentId:"0807",
        name:'TÍCH',
        title:"HÀNG 9",
    },
    {
        id:'0917',
        parentId:"0807",
        name:'ĐỨC',
        title:"HÀNG 9",
        description1:"LIỆT SỸ",
    },
    {
        id:'0918',
        parentId:"0809",
        name:'HUẤN',
        title:"HÀNG 9",
    },
    {
        id:'0919',
        parentId:"0809",
        name:'LUYỆN',
        title:"HÀNG 9",
    },
    {
        id:'0920',
        parentId:"0809",
        name:'THẮNG',
        title:"HÀNG 9",
    },
    {
        id:'0921',
        parentId:"0811",
        name:'HIẾN',
        title:"HÀNG 9",
    },
    {
        id:'0922',
        parentId:"0811",
        name:'TIỀN',
        title:"HÀNG 9",
    },
    {
        id:'0923',
        parentId:"0811",
        name:'QUY',
        title:"HÀNG 9",
    },
    {
        id:'0924',
        parentId:"0811",
        name:'VĨNH',
        title:"HÀNG 9",
    },
    {
        id:'0925',
        parentId:"0812",
        name:'THẠO',
        title:"HÀNG 9",
    },
    {
        id:'0926',
        parentId:"0812",
        name:'HƯNG',
        title:"HÀNG 9",
    },
    {
        id:'0927',
        parentId:"0812",
        name:'YÊN',
        title:"HÀNG 9",
    },
    {
        id:'0928',
        parentId:"0813",
        name:'ĐỨC',
        title:"HÀNG 9",
        description1:"LIỆT SỸ",
    },
    {
        id:'0929',
        parentId:"0813",
        name:'NGUYÊN',
        title:"HÀNG 9",
    },
    {
        id:'0930',
        parentId:"0814",
        name:'VIỄN',
        title:"HÀNG 9",
        description1:"TAI NẠN CHẾT",
    },
    {
        id:'0931',
        parentId:"0814",
        name:'THÊM',
        title:"HÀNG 9",
    },
    {
        id:'0932',
        parentId:"0815",
        name:'VIỆT',
        title:"HÀNG 9",
        description1:"VIỆT",
        description2:"TRIỆU THỊ MINH TÂM",
        description3:"SINH 2 CON GÁI",
    },
    {
        id:'0933',
        parentId:"0815",
        name:'TUẤN',
        title:"HÀNG 9",
        description1:"TUẤN",
        description2:"VÕ THỊ KIM ANH",
        description3:"SINH 1 TRAI 1 GÁI",
    },
    {
        id:'0934',
        parentId:"0815",
        name:'HÙNG',
        title:"HÀNG 9",
        description1:"HÙNG",
        description2:"VŨ THỊ LÂN",
    },
    {
        id:'0935',
        parentId:"0816",
        name:'ĐỨC',
        title:"HÀNG 9",
    },
    {
        id:'1001',
        parentId:"0901",
        name:'DANH',
        title:"HÀNG 10",
    },
    {
        id:'1002',
        parentId:"0901",
        name:'QUYỀN',
        title:"HÀNG 10",
    },
    {
        id:'1003',
        parentId:"0905",
        name:'LỘC',
        title:"HÀNG 10",
    },
    {
        id:'1004',
        parentId:"0905",
        name:'KHANG',
        title:"HÀNG 10",
    },
    {
        id:'1005',
        parentId:"0912",
        name:'ĐỨC',
        title:"HÀNG 10",
    },
    {
        id:'1006',
        parentId:"0913",
        name:'QUYỀN',
        title:"HÀNG 10",
    },
    {
        id:'1007',
        parentId:"0913",
        name:'TRỨC',
        title:"HÀNG 10",
    },
    {
        id:'1008',
        parentId:"0914",
        name:'HIẾN',
        title:"HÀNG 10",
    },
    {
        id:'1009',
        parentId:"0915",
        name:'DƯỢC',
        title:"HÀNG 10",
    },
    {
        id:'1010',
        parentId:"0915",
        name:'HÀ',
        title:"HÀNG 10",
    },
    {
        id:'1011',
        parentId:"0915",
        name:'ĐIỆP',
        title:"HÀNG 10",
    },
    {
        id:'1012',
        parentId:"0915",
        name:'NAM',
        title:"HÀNG 10",
    },
    {
        id:'1013',
        parentId:"0916",
        name:'THIỆN',
        title:"HÀNG 10",
    },
    {
        id:'1014',
        parentId:"0916",
        name:'LONG',
        title:"HÀNG 10",
    },
    {
        id:'1015',
        parentId:"0918",
        name:'KIÊN',
        title:"HÀNG 10",
    },
    {
        id:'1016',
        parentId:"0918",
        name:'NAM',
        title:"HÀNG 10",
    },
    {
        id:'1017',
        parentId:"0919",
        name:'VŨ',
        title:"HÀNG 10",
    },
    {
        id:'10181',
        parentId:"0919",
        name:'LỰC',
        title:"HÀNG 10",
    },
    {
        id:'1019',
        parentId:"0921",
        name:'HIỂN',
        title:"HÀNG 10",
    },
    {
        id:'1020',
        parentId:"0922",
        name:'TRƯỜNG',
        title:"HÀNG 10",
    },
    {
        id:'1021',
        parentId:"0922",
        name:'TÔN',
        title:"HÀNG 10",
    },
    {
        id:'1022',
        parentId:"0923",
        name:'THANH',
        title:"HÀNG 10",
    },
    {
        id:'1023',
        parentId:"0923",
        name:'BẢO',
        title:"HÀNG 10",
    },
    {
        id:'1024',
        parentId:"0924",
        name:'DUY',
        title:"HÀNG 10",
    },
    {
        id:'1025',
        parentId:"0925",
        name:'HIỀN',
        title:"HÀNG 10",
    },
    {
        id:'1026',
        parentId:"0925",
        name:'HẬU',
        title:"HÀNG 10",
    },
    {
        id:'1027',
        parentId:"0925",
        name:'PHƯƠNG',
        title:"HÀNG 10",
    },
    {
        id:'1028',
        parentId:"0925",
        name:'ĐÔNG',
        title:"HÀNG 10",
    },
    {
        id:'1029',
        parentId:"0925",
        name:'NAM',
        title:"HÀNG 10",
    },
    {
        id:'1030',
        parentId:"0926",
        name:'NAM',
        title:"HÀNG 10",
    },
    {
        id:'1031',
        parentId:"0929",
        name:'BINH',
        title:"HÀNG 10",
    },
    {
        id:'1032',
        parentId:"0929",
        name:'HÀ',
        title:"HÀNG 10",
    },
    {
        id:'1033',
        parentId:"0931",
        name:'THANH',
        title:"HÀNG 10",
    },
    {
        id:'1034',
        parentId:"0932",
        name:' ',
        title:"HÀNG 10",
    },
    {
        id:'1035',
        parentId:"0933",
        name:'TRƯỜNG',
        title:"HÀNG 10",
    },
    {
        id:'1036',
        parentId:"0934",
        name:'KIÊN',
        title:"HÀNG 10",
    },
    {
        id:'1037',
        parentId:"0935",
        name:' ',
        title:"HÀNG 10",
    },
];



